package settings

import (
	"encoding/json"
	"fmt"

	"github.com/CircleCI-Public/chunk-cli/internal/config"
)

// hookEntry is one hook command within a hook group.
type hookEntry struct {
	Type    string `json:"type"`
	Command string `json:"command"`
	Timeout int    `json:"timeout"`
}

// hookGroup is a group of hooks filtered by matcher.
// Matcher is omitted for hook types that don't use it (e.g. Stop).
type hookGroup struct {
	Matcher string      `json:"matcher,omitempty"`
	Hooks   []hookEntry `json:"hooks"`
}

// settingsJSON is the .claude/settings.json structure.
type settingsJSON struct {
	Schema      string                 `json:"$schema"`
	Comment     string                 `json:"_comment"`
	Permissions map[string][]string    `json:"permissions"`
	Hooks       map[string][]hookGroup `json:"hooks,omitempty"`
}

// codexHooksJSON is the .codex/hooks.json structure — hooks only, no metadata or permissions.
type codexHooksJSON struct {
	Hooks map[string][]hookGroup `json:"hooks,omitempty"`
}

// Build generates .claude/settings.json content from commands.
// It creates:
//   - A PreToolUse hook matching "Bash(git commit*)" that runs each command before commits.
//   - A Stop hook that runs "chunk validate" after every session.
func Build(commands []config.Command) ([]byte, error) {
	hooks := make([]hookEntry, 0, len(commands))
	for _, cmd := range commands {
		timeout := cmd.Timeout
		if timeout == 0 {
			timeout = 60
		}
		hooks = append(hooks, hookEntry{
			Type:    "command",
			Command: fmt.Sprintf("cd ${CLAUDE_PROJECT_DIR:-.} && %s", cmd.Run),
			Timeout: timeout,
		})
	}

	s := settingsJSON{
		Schema:  "https://json.schemastore.org/claude-code-settings.json",
		Comment: "Generated by chunk init.",
		Permissions: map[string][]string{
			"allow": {"Bash(chunk:*)"},
		},
	}

	if len(hooks) > 0 {
		// Compute a Stop hook timeout that covers all commands running sequentially,
		// capped at 600s to avoid exceeding Claude Code's maximum hook timeout.
		const maxStopTimeout = 600
		stopTimeout := 30 // base buffer
		for _, cmd := range commands {
			t := cmd.Timeout
			if t == 0 {
				t = 300
			}
			stopTimeout += t
		}
		if stopTimeout > maxStopTimeout {
			stopTimeout = maxStopTimeout
		}

		s.Hooks = map[string][]hookGroup{
			"PreToolUse": {
				{
					Matcher: CommitMatcher,
					Hooks:   hooks,
				},
			},
			// Stop hook: runs validation at session end.
			"Stop": {
				{
					Hooks: []hookEntry{
						{
							Type:    "command",
							Command: "chunk validate",
							Timeout: stopTimeout,
						},
					},
				},
			},
		}
	}

	return json.MarshalIndent(s, "", "  ")
}

// BuildCodex generates .codex/hooks.json content from commands.
// Produces the same hook structure as Build but without Claude Code-specific
// metadata ($schema, _comment) and without a permissions block. Commands run
// as-is; Codex sets CWD to the project root before invoking hooks.
func BuildCodex(commands []config.Command) ([]byte, error) {
	const maxStopTimeout = 600
	stopTimeout := 30
	hooks := make([]hookEntry, 0, len(commands))
	for _, cmd := range commands {
		timeout := cmd.Timeout
		if timeout == 0 {
			timeout = 60
		}
		stopTimeout += timeout
		hooks = append(hooks, hookEntry{
			Type:    "command",
			Command: cmd.Run,
			Timeout: timeout,
		})
	}
	if stopTimeout > maxStopTimeout {
		stopTimeout = maxStopTimeout
	}

	s := codexHooksJSON{}

	if len(hooks) > 0 {

		s.Hooks = map[string][]hookGroup{
			"PreToolUse": {
				{
					Matcher: CommitMatcher,
					Hooks:   hooks,
				},
			},
			"Stop": {
				{
					Hooks: []hookEntry{
						{
							Type:    "command",
							Command: "chunk validate",
							Timeout: stopTimeout,
						},
					},
				},
			},
		}
	}

	return json.MarshalIndent(s, "", "  ")
}
